// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
///
///

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEWuYfTB8ZPFikUAZPZ-CcvXxFWfyLUdc',
    appId: '1:261391729964:web:1d116de0ce5c6afded5889',
    messagingSenderId: '261391729964',
    projectId: 'passion-9985b',
    authDomain: 'passion-9985b.firebaseapp.com',
    storageBucket: 'passion-9985b.appspot.com',
    measurementId: 'G-54NR8D58K3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8Oa-6vRxJWSpHHkxQGJ6b5NRc5uq0aEE',
    appId: '1:261391729964:android:9e24acd3b660dae8ed5889',
    messagingSenderId: '261391729964',
    projectId: 'passion-9985b',
    storageBucket: 'passion-9985b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4bQEua_idDHNCdoioaYrFkn4952kiFmA',
    appId: '1:261391729964:ios:0e928ca6c6068535ed5889',
    messagingSenderId: '261391729964',
    projectId: 'passion-9985b',
    storageBucket: 'passion-9985b.appspot.com',
    iosClientId:
        '261391729964-37fuqj1jqflp6t5n9enj93cifb7mg256.apps.googleusercontent.com',
    iosBundleId: 'com.example.shaghaf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4bQEua_idDHNCdoioaYrFkn4952kiFmA',
    appId: '1:261391729964:ios:0e928ca6c6068535ed5889',
    messagingSenderId: '261391729964',
    projectId: 'passion-9985b',
    storageBucket: 'passion-9985b.appspot.com',
    iosClientId:
        '261391729964-37fuqj1jqflp6t5n9enj93cifb7mg256.apps.googleusercontent.com',
    iosBundleId: 'com.example.shaghaf',
  );
}
